#!/bin/sh
acpi | sed "s/Battery [0-9]: //;s/[Dd]ischarging, //;s/[Nn]ot charging, /! /;s/[Cc]harging, /ϟ/;s/[Uu]nknown, /? /;s/[Ff]ull, /❤/;s/[0-9][0-9]%, /&&/;s/ [0-9]%, /!l   l /1;s/[1-2][0-9]%, /lI   l /1;s/[3-5][0-9]%, /lII  l /1;s/[6-7][0-9]%, /lIII l /1;s/[8-9][0-9]%, /lIIIIl /1;s/100%, //1;s~,.*~~"; exit
